
package zwo.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sat Jan 05 08:20:47 CET 2019
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getDatumResponse", namespace = "http://zwo/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDatumResponse", namespace = "http://zwo/")

public class GetDatumResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<zwo.Taxifahrt> _return;

    public java.util.ArrayList<zwo.Taxifahrt> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<zwo.Taxifahrt> new_return)  {
        this._return = new_return;
    }

}

