
package zwo.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sat Jan 05 08:20:46 CET 2019
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getDatum", namespace = "http://zwo/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDatum", namespace = "http://zwo/")

public class GetDatum {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

