package zwo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-01-05T08:25:41.019+01:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://zwo/", name = "Taxidaten")
@XmlSeeAlso({ObjectFactory.class})
public interface Taxidaten {

    @WebMethod(action = "urn:GetDatum")
    @RequestWrapper(localName = "getDatum", targetNamespace = "http://zwo/", className = "zwo.GetDatum")
    @ResponseWrapper(localName = "getDatumResponse", targetNamespace = "http://zwo/", className = "zwo.GetDatumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<zwo.Taxifahrt> getDatum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
