package zwo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-01-05T08:25:41.032+01:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "TaxidatenImplService",
                  wsdlLocation = "file:/C:/Users/admin/workspace/MeilensteinZwei_New/WebContent/wsdl/taxidatenimpl.wsdl",
                  targetNamespace = "http://zwo/")
public class TaxidatenImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://zwo/", "TaxidatenImplService");
    public final static QName TaxidatenImplPort = new QName("http://zwo/", "TaxidatenImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/admin/workspace/MeilensteinZwei_New/WebContent/wsdl/taxidatenimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaxidatenImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/admin/workspace/MeilensteinZwei_New/WebContent/wsdl/taxidatenimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaxidatenImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaxidatenImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxidatenImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaxidatenImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaxidatenImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaxidatenImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Taxidaten
     */
    @WebEndpoint(name = "TaxidatenImplPort")
    public Taxidaten getTaxidatenImplPort() {
        return super.getPort(TaxidatenImplPort, Taxidaten.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Taxidaten
     */
    @WebEndpoint(name = "TaxidatenImplPort")
    public Taxidaten getTaxidatenImplPort(WebServiceFeature... features) {
        return super.getPort(TaxidatenImplPort, Taxidaten.class, features);
    }

}
