
package zwo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-04T14:05:31.353+01:00
 * Generated source version: 3.2.6
 *
 */
public final class Taxidaten_TaxidatenImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://zwo/", "TaxidatenImplService");

    private Taxidaten_TaxidatenImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TaxidatenImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TaxidatenImplService ss = new TaxidatenImplService(wsdlURL, SERVICE_NAME);
        Taxidaten port = ss.getTaxidatenImplPort();

        {
        System.out.println("Invoking getDatum...");
        int _getDatum_arg0 = -986269843;
        java.util.List<zwo.Taxifahrt> _getDatum__return = port.getDatum(_getDatum_arg0);
        System.out.println("getDatum.result=" + _getDatum__return);


        }

        System.exit(0);
    }

}
